- hosts: all
  become: true
  tasks:
   - name: Hi. I ensure connecting to the machine
     ping:
   - name: Add JDK ppa
     apt_repository: repo=ppa:openjdk-r/ppa
   - name: Install JDK
     apt: name=openjdk-7-jdk state=present update-cache=yes force=yes
   - name: Install Tomcat Server
     apt: name={{ item }} state=present
     with_items:
      - tomcat7
      - tomcat7-admin
   - name: Remove all JAVA_HOME variables in Tomcat conf
     lineinfile:
      dest='/etc/default/tomcat7'
      regexp='^JAVA_HOME'
      state=absent
   - name: Add correct JAVA_HOME variable in Tomcat conf
     lineinfile:
      dest='/etc/default/tomcat7'
      insertafter='^#JAVA_HOME'
      line='JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/'
   - name: Change owner of tomcat7 webapps folder to root
     file:
      path=/var/lib/tomcat7/webapps/
      owner=root
      group=root
      recurse=yes
   - name: Downloading Jenkins war file
     local_action:
      get_url
       url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war
       dest=/home/jenkins.war
   - name: Upload Jenkins to Tomcat webapps
     copy:
      src=/home/jenkins.war
      dest=/var/lib/tomcat7/webapps/jenkins.war
   - name: Reversing owner of tomcat7 webapps folder to tomcat7
     file:
      path=/var/lib/tomcat7/webapps/
      owner=tomcat7
      group=tomcat7
      recurse=yes
   - name: Setting owner of tomcat7 share folder to tomcat7 to enable Jenkins
     file:
      path=/usr/share/tomcat7/
      owner=tomcat7
      group=tomcat7
      recurse=yes
   - name: Ensure Tomcat 7 is started and enabled on boot with Jenkins running
     service: name=tomcat7 state=started enabled=yes